### PR TITLE
triagile 2016 - fixes bug with logging not working for multiselect

### PR DESCRIPTION
**Pull request by srmelody**
@dawnTestCode I think this will work without pulling in lodash.  It uses the plain old boring array.forEach so it should work across browsers.

### CODE REVIEW

**Comment by genecyber** [comment]
Looping over each id and logging those row details should work just fine.

**Comment by dawnTestCode** [comment]
But it's boring!

What is loadash?

**Comment by srmelody** [comment]
lodash is a library that sort of fills in the blanks of javascript - https://lodash.com
it's starting to get out of fashion due to the release of ecmascript 6 (javascript v.next) and 7 which added some of the functions that folks were using lodash for.

I looked at the bootstrap table code and it wasn't obvious to me that it could support multiple row addition.  but maybe i'm missing something. :)

**Comment by dawnTestCode** [comment]
Thanks. I found the same that bootstrap didn't seem to clearly support multiple row addition.

Thanks for the PRs :)

**Pull request merged**
